# Generated by Django 4.1.3 on 2022-12-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingspa',
            name='service',
        ),
        migrations.AddField(
            model_name='bookingspa',
            name='time_service',
            field=models.FloatField(default=0),
        ),
    ]
