# Generated by Django 4.1.3 on 2022-12-07 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_itemcleaningroom_price_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('time_minutes', models.IntegerField()),
                ('commission_percentage', models.FloatField()),
                ('price', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, max_length=25, null=True)),
                ('amount', models.FloatField()),
                ('price_amount', models.FloatField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.supplie')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.service')),
            ],
        ),
    ]
