# Generated by Django 4.1.3 on 2022-12-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcleaningroom',
            name='price_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
