# Generated by Django 4.1.3 on 2022-12-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='created',
            field=models.DateField(),
        ),
    ]
