# Generated by Django 4.1.3 on 2022-12-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_alter_expenses_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='assistant',
            field=models.CharField(default='System', max_length=25),
        ),
    ]
