# Generated by Django 4.1.3 on 2023-01-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_alter_sale_assistant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
