# Generated by Django 4.1.3 on 2023-02-04 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_itemcleaningroom_price_amount'),
        ('administrator', '0005_alter_sale_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedCosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.distributor')),
            ],
        ),
    ]
